security:
  readonly: false
  enable_auth: false
  cookie:
    same_site: lax
    secure: false

database:
  file:
    extension: yaml
    folder: /perses

provisioning:
  folders:
    - /etc/perses/resources

frontend:
  explorer:
    enable: true

ephemeral_dashboard:
  enable: true
  cleanup_interval: 1h